# This is a sample Bitbucket Pipelines configuration for a ReactJS project.

image: node:16.3.0-alpine3.11

pipelines:
  branches:
    master:
    - step:
        name: Build and Test
        image: node:latest
        script:
          - npm install
          - npm test
          - npm run build
    custom:
      production:
        - step:
            name: Deploy to production
            image: node:latest
            script:
              - npm install
              - npm run build
            artifacts:
              - build/**
        - step:
            name: Deploy to production
            deployment: production
            script:
              - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: "$S3_BUCKET"
                LOCAL_PATH: "dist/*"
                ACL: "public-read"
