# This is a sample Bitbucket Pipelines configuration for a ReactJS project.

image: public.ecr.aws/sam/build-nodejs14.x

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install

    - step:
        name: Run Tests
        caches:
          - node
        script:
          - npm test

    - step:
        name: Build Production Code
        caches:
          - node
        script:
          - npm run build
    - step:
        name: Build and Package
        script:
          - sam build
          - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
