# This is a sample Bitbucket Pipelines configuration for a ReactJS project.

image: public.ecr.aws/sam/build-nodejs14.x
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install
    - step:
        name: Build Production Code
        caches:
          - node
        script:
          - npm run build
    - step:
        name: Deploy to S3
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-east-1'
              S3_BUCKET: 'bbci-example-s3-deploy'
              LOCAL_PATH: 'artifact'
              ACL: 'public-read'