image: node:14.16.0

pipelines:
  default:
    - step:
        name: Install and Build
        caches:
          - node
        script:
          - npm install
          - npm run build
    - step:
        name: Deploy to AWS
        deployment: production
        trigger: manual
        script:
          - apt-get update && apt-get install -y zip
          - zip -r app.zip build/
          - apt-get install -y awscli
          - aws s3 cp app.zip s3://harry-potter-graphql-jdavidcor/app.zip
